project:
  type: website
  output-dir: _site
  render:
    - about/index.qmd
    - about/overview.qmd
    - about/syllabus.qmd
    - chapters/*/chapter*.qmd
    - chapters/*/slides/*.qmd
    - chapters/*/slides/*.Rmd
    - resources/*
    - assets/styles.css
website:
  title: "Introduction to Data Science in R"
  sidebar:
    logo: assets/images/course_logo.png
    style: "docked"
    search: true
    tools:
      - icon: github
        href: https://github.com/xcit-courses/ds-R-intro
        text: "GitHub"
      - icon: cloud-fill
        href: https://posit.cloud/
        text: "RStudio Cloud"
      - icon: person-fill
        href: https://uni.lu
        text: "UniLu"
    contents:
      - text: Home
        href: about/index.qmd
      - section: Course Information
        contents:
          - text: Overview
            href: about/overview.qmd
          - text: Syllabus
            href: about/syllabus.qmd

      - section: Chapters
        contents:
          - text: Chapter 1 - Programming in R
            href: chapters/chapter1/chapter1.qmd
          - text: Chapter 2 - Data visualization
            href: chapters/chapter2/chapter2.qmd
          - text: Chapter 3 - ggplot2
            href: chapters/chapter3/chapter3.qmd                     
          - text: Chapter 4 - importing and data.frames
            href: chapters/chapter4/chapter4.qmd                     
          - text: Chapter 5 - pipes
            href: chapters/chapter5/chapter5.qmd                     
          - text: Chapter 6 - tidy data
            href: chapters/chapter6/chapter6.qmd                     

      - text: Resources
        href: resources/resources.md

  page-footer:
    left: ""
    right: "Built with [Quarto](https://quarto.org/)"
  page-navigation: true

book:
  chapters:
    - about/index.qmd
    - part: "Course Information"
      chapters:
        - about/overview.qmd
        - about/syllabus.qmd
    - part: "Chapters"
      chapters:
        - chapters/chapter1/chapter1.qmd            
        - chapters/chapter2/chapter2.qmd            
        - chapters/chapter3/chapter3.qmd            
        - chapters/chapter4/chapter4.qmd            
        - chapters/chapter5/chapter5.qmd            
        - chapters/chapter6/chapter6.qmd                          
    - resources/resources.md

format:
  html:
    theme:
      - lux
      - assets/styles.css
    toc: true
    code-copy: true
    code-overflow: wrap
    link-external-newwindow: true
    color-scheme: auto
